version: "3"
services:
  web:
    build: ./deploy/web
    restart: unless-stopped
    ports:
      - 8000:8000
  bot:
    build: ./deploy/bot
    restart: unless-stopped
    ports:
      - 1337:1337
    environment:
      - FLAG=DH{FLAG}