version: '3'

services:
  narrow_date:
    build: ./init/
    container_name: narrow_date
    volumes:
            - ./app:/var/www/html
    ports:
            - "8080:80"
    links:
            - database

  database:
    image: mariadb:10.5.13
    restart: always
    container_name: narrow_date_db
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=e25308a23fd811a2c3254a48fa5098ac
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
