services:
  nginx.com:
    container_name: nginx.com
    build:
      context: ./deploy/nginx
    ports:
      - "8001:8001"
    depends_on:
      - app.com
  app.com:
    container_name: app.com
    build:
      context: ./deploy/app
    ports:
      - "8002:8002"
    
