version: "3.9"

services:
  backend:
    build:
      context: deploy/backend/
    networks:
      - internal
  app:
    build:
      context: deploy/app/
    depends_on:
      - backend
    networks:
      - internal
    ports:
      - "7000:7000"

networks:
  internal:
